locale: "en-US"
site_theme: "default"
title: "Laura Villalobos"
title_separator: "-"
name: &name "Laura Villalobos"
description: &description "Academic website of Laura Villalobos"
url: "https://lavifi.github.io"
baseurl: ""
repository: "lavifi/lavifi.github.io"

author:
  avatar: "profile.png"
  name: "Laura Villalobos"
  bio: "Environmental and development economist"
  location: "Salisbury, Maryland"
  employer: "Salisbury University"
  uri:
  email:
  googlescholar: "https://scholar.google.com/citations?user=P4AfS1kAAAAJ&hl=en"
  orcid:
  github: "lavifi"
  linkedin:
  twitter:

publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

comments:
  provider:

atom_feed:
  hide: true

analytics:
  provider: "false"

include:
  - .htaccess
  - _pages
  - files

exclude:
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Dockerfile
  - Gemfile
  - LICENSE
  - node_modules
  - package.json*
  - README.md
  - vendor

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
